package de.unhd.ugit.command;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.command.CommandExecutor;
import de.unhd.ugit.main;

public class cmd_clearmychat implements CommandExecutor{
	static String game = main.game;
	static String prefix = main.prefix;
	
	  public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
		if (label.equalsIgnoreCase("clearmychat") | label.equalsIgnoreCase("cmc")) {   
	      if (sender instanceof Player) {
	        Player player = (Player)sender;
	        if (args.length == 0) {
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	          player.sendMessage("§8");
	        } 
	        
	        if (args.length == 1) {
		      if (args[0].equalsIgnoreCase("version")) {
		       player.sendMessage(String.valueOf(prefix) + "§aClearMyChatGit version (Build 1.0.0 | implement in UGit) by HerrUngelachtHD");
		      }
	        }
	      }
		}
		return false;
	  }
	  
}
